import './globals.css'
import Navbar from "./components/navigation/navbar/navbar";
import NewPrompt from './components/prompt/NewPrompt';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="flex flex-col min-h-screen">
        <Navbar />
        {children}
      </body>
    </html>
  )
}
